services:
  app:
    image: 'ryanmcintosh1/project1:latest'
    container_name: project1-container
    ports:
      - 7400:7400
    environment:
      - Endpoint=jdbc:postgresql://database-1.c7kojdmg9vdy.us-east-1.rds.amazonaws.com:5432/postgres
      - DBUsername=postgres
      - DBPassword=password

  prom:
    image: 'prom/prometheus'
    container_name: prom-container
      #Specify the prometheus file in our host system and move it into the container!
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
  graf:
    image: 'grafana/grafana'
    ports:
      - 8000:3000
